# .github/workflows/daily-download.yml
name: Get IPO Details

on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Get Latest IPO Details

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        id: install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch and Filter IPO Details
        id: fetch
        run: python fetch.py

      - name: Send mail
        env:
          IPO: ${{steps.fetch.outputs.IPO}}
          IPO_LEN: ${{steps.fetch.outputs.IPO_LEN}}
        if: ${{steps.fetch.outputs.IPO_LEN}} > 0
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: IPO Details
          to: ${{secrets.MAIL_ID_1}}
          from: Luke Skywalker
          body: ${{steps.fetch.outputs.IPO}}
